In [4]:
import numpy as np

W = np.array([[5.0], [3.0]])
print(W)
x = np.array([[1.0, 5.0]])

# すべての要素が0の行列
zeros = np.zeros([1, 5])
print(zeros)
# すべての要素が1の行列
ones = np.ones(W.shape)
print(ones)

[[5.]
 [3.]]
[[0. 0. 0. 0. 0.]]
[[1.]
 [1.]]
